def find_number(arr, query):
    if len(arr)==0:
        return -1
    for i in range(0,len(arr)-1):
        if arr[i]==query:
            return i

    return -1



"""
389. Find the Difference
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        for char in t:
            if t.count(char) != s.count(char):
                return char

        return None

"""
136. Single Number
Given a non-empty array of integers nums, every element appears twice except for one. Find that single one.
You must implement a solution with a linear runtime complexity and use only constant extra space.
"""
def singleNumber(nums):
    result = 0
    for num in nums:
        result ^= num
        print("result ",result)
    return result

# Example usage:
nums = [2,2,1,1,3,4,4,6,6]
print(singleNumber(nums))
print(singleNumber([1,1,2,2,3,3,4]))

